version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lead-tracker-backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:5000}
    ports:
      - "5000:5000"
    networks:
      - appnet
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lead-tracker-frontend
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5000/api}
      - VITE_API_FRONTEND_URL=${VITE_API_FRONTEND_URL:-http://localhost:5173}
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge
